---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true

requirements:
    requiredRam:        1.0
    check:
        - ram
        - power
        - root
    required:
        - ram
        - root
